# Generated by Django 4.2.4 on 2023-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='entity',
            name='activity_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код вида деятельности'),
        ),
        migrations.AddField(
            model_name='entity',
            name='activity_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='вид деятельности'),
        ),
        migrations.AddField(
            model_name='entity',
            name='fio',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='entity',
            name='full_name_bel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование юр. лица (бел)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='last_event_date',
            field=models.DateTimeField(null=True, verbose_name='Дата последней записи в ЕГР'),
        ),
        migrations.AddField(
            model_name='entity',
            name='short_name_bel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое наименование (бел)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='pan',
            field=models.PositiveIntegerField(verbose_name='Регистрационный номер'),
        ),
    ]
