# Generated by Django 4.2.4 on 2023-08-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrn_info', '0003_alter_entity_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone_number',
            field=models.CharField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='short_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое наименование'),
        ),
    ]
