# Generated by Django 4.2.2 on 2023-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('category_url', models.URLField(verbose_name='Ссылка на категорию')),
                ('gender', models.CharField(max_length=15, verbose_name='Пол')),
                ('availability', models.CharField(max_length=100, verbose_name='Наличие')),
                ('margin', models.PositiveIntegerField(verbose_name='Наценка(%)')),
                ('delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доставка(РУБ)')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('product_type', models.CharField(max_length=100, verbose_name='Тип товаров')),
                ('name_pattern', models.CharField(max_length=100, verbose_name='Шаблон наименования товаров')),
                ('badge', models.TextField(verbose_name='наклейка')),
                ('tags', models.CharField(max_length=100, verbose_name='Теги')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('meta_description', models.CharField(max_length=100, verbose_name='META description')),
                ('meta_keywords', models.CharField(max_length=100, verbose_name='META Keywords')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
            ],
        ),
    ]
