# Generated by Django 4.2.2 on 2023-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_category_parsed_csv_alter_category_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parsed_csv',
            field=models.FileField(blank=True, upload_to='parser/parsed', verbose_name='Готовый csv'),
        ),
    ]
