# Generated by Django 4.2.2 on 2023-07-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(max_length=100, verbose_name='META description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Порядок')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('meta_keywords', models.CharField(max_length=100, verbose_name='META keywords')),
                ('meta_description', models.TextField(verbose_name='META description')),
                ('showcase_link', models.CharField(max_length=100, verbose_name='Ссылка на витрину')),
                ('webasyst_category_id', models.PositiveIntegerField(verbose_name='ID категории в webasyst')),
                ('category_description', models.TextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.category')),
            ],
        ),
    ]
