# Generated by Django 4.2.2 on 2023-07-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='position',
        ),
    ]
