# Generated by Django 4.2.2 on 2023-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parsed_csv',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, max_length=15, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
