version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - egr_db:/var/lib/postgresql/data/pgdata
  web:
    build: .
    volumes:
      - ./egrn:/app
    env_file:
      - .env
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - DEBUG=${DEBUG}
    expose:
      - "${BACKEND_PORT}"
    depends_on:
      - db
  nginx:
    image: anroe/nginx-cookie-flag
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./egrn/static:/static
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - web
      - db

volumes:
  egr_db:
    name: "egr_db"